listA=[1,2,3,4,5,6,7,8,9,0]
print(listA)
listA.append(-1)
print(listA)
listA.sort()
print("Sorting : ",listA)
listA.sort(reverse=True)
print("Sorting in reverse : ",listA)
listA.insert(4,4.5)
print("After Insert : ",listA)
listA.pop()
print("After pop : ",listA)
listA.remove(4.5)
print("After remove : ",listA)

listC=listA.copy()
print("Printing list C : ",listC)
listC.sort()
print(listC)